package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"

	"github.com/daana-code/db-testkit/pkg/docker"
)

// GenerateGoConstants generates a Go source file with database configuration constants.
// The output file is created at the specified path, with parent directories created as needed.
func GenerateGoConstants(creds *docker.TestDBCredentials, outputPath string) error {
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	tmpl := `// Code generated by db-testkit. DO NOT EDIT.
// Generated on: {{.Timestamp}}
// Source: docker-compose.yml

package project

// Test database configuration constants extracted from docker-compose.yml
// These values are the single source of truth for automated testing credentials

const (
	// Customer database configuration (db-test-customer service)
	DefaultCustomerHost     = "{{.CustomerHost}}"
	DefaultCustomerPort     = {{.CustomerPort}}
	DefaultCustomerUser     = "{{.CustomerUser}}"
	DefaultCustomerPassword = "{{.CustomerPassword}}"
	DefaultCustomerDB       = "{{.CustomerDB}}"

	// Internal database configuration (db-test-internal service)
	DefaultInternalHost     = "{{.InternalHost}}"
	DefaultInternalPort     = {{.InternalPort}}
	DefaultInternalUser     = "{{.InternalUser}}"
	DefaultInternalPassword = "{{.InternalPassword}}"
	DefaultInternalDB       = "{{.InternalDB}}"

	// Common configuration
	DefaultSSLMode = "disable"
)
`

	t, err := template.New("generated-config").Parse(tmpl)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer file.Close()

	data := struct {
		*docker.TestDBCredentials
		Timestamp string
	}{
		TestDBCredentials: creds,
		Timestamp:         time.Now().Format("2006-01-02 15:04:05 MST"),
	}

	return t.Execute(file, data)
}
